packages:
  - playground/*

catalog:
  '@feathersjs/adapter-commons': '^5.0.46'
  '@feathersjs/authentication': '^5.0.46'
  '@feathersjs/authentication-client': '^5.0.46'
  '@feathersjs/authentication-local': '^5.0.46'
  '@feathersjs/cli': '5.0.46'
  '@feathersjs/configuration': '^5.0.46'
  '@feathersjs/errors': '^5.0.46'
  '@feathersjs/express': '^5.0.46'
  '@feathersjs/feathers': '^5.0.46'
  '@feathersjs/koa': '^5.0.46'
  '@feathersjs/memory': '^5.0.46'
  '@feathersjs/rest-client': '^5.0.46'
  '@feathersjs/schema': '^5.0.46'
  '@feathersjs/socketio': '^5.0.46'
  '@feathersjs/socketio-client': '^5.0.46'
  '@feathersjs/transport-commons': '^5.0.46'
  '@feathersjs/typebox': '^5.0.46'
  '@gabortorma/antfu-eslint-config': '3.2.0'
  '@gabortorma/nuxt-eslint-layer': '1.0.0'
  '@pinia/nuxt': '0.11.3'
  '@types/mocha': '^10.0.10'
  '@types/node': '^22.20.0'
  'axios': '^1.18.1'
  'compression': '^1.8.1'
  'cross-env': '10.1.0'
  'mocha': '11.7.6'
  'nodemon': '^3.1.14'
  'nuxt': '4.4.8'
  'ofetch': '^1.5.1'
  'pinia': '3.0.4'
  'prettier': '^3.9.4'
  'shx': '^0.4.0'
  'socket.io-client': '^4.8.3'
  'ts-node': '^10.9.2'
  'typescript': '5.9.3'
  'winston': '^3.19.0'
